### ISSUE TITLE
Hard to read labels

### ISSUE THREAD

**Issue by RivenSkaye** [TimeTraveller-San/whatsapp.moe#1]
With automatic color extraction from the provided image, the date labels (scroll up, you immediately see "Today" appear up top) can become really hard to read.
Suggested fix: Add menu item to select the extracted colors to use

**Comment by vaibkumr** [comment]
Will be done ASAP 
several other changes also need be done because of the latest updates in whatsapp

**Comment by vaibkumr** [comment]
All colors fixed as per the latest whatsapp update
Some images yield bad colors after extractions for which custom color option can be used.
